//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationFormField
    {
        public int AppFormFieldId { get; set; }
        public Nullable<int> AppFormGroupID { get; set; }
        public string DisplayName { get; set; }
        public string FieldName { get; set; }
        public string FieldDataType { get; set; }
        public Nullable<byte> FieldOrder { get; set; }
        public string FieldDropDownValue { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
    }
}
