//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using EduRp.Data.Core.Foundation;
    using System;
    using System.Collections.Generic;
    

    public partial class ApplicationFormFeeAssociation:BaseEntity
    {
        public int AppFormFeeId { get; set; }
        public int AppFormTemplateId { get; set; }
        public int FeeId { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<byte> Orderby { get; set; }
    }
}
