//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using EduRp.Data.Core.Foundation;
    using System;
    using System.Collections.Generic;
    
    public partial class BulkLoadMaster : BaseEntity
    {
        public int BulkLoadMasterId { get; set; }
        public Nullable<int> UnivercityID { get; set; }
        public string ModuleName { get; set; }
        public string FileName { get; set; }
        public string SQLLoaderJobName { get; set; }
    }
}
