//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using EduRp.Data.Core.Foundation;
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster : BaseEntity
    {
        public int UniversityId { get; set; }
        public int EmployeeId { get; set; }
        public string EmployeeNumber { get; set; }
        public string FullName { get; set; }
        public string NIDN { get; set; }
        public string NIP { get; set; }
        public string HP { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public string Religion { get; set; }
        public string MaritalStatus { get; set; }
        public string Nationality { get; set; }
        public string PhoneNumber { get; set; }
        public string LandLineNumber { get; set; }
        public Nullable<System.DateTime> DateofJoining { get; set; }
        public Nullable<int> NoOfYearsOfService { get; set; }
        public Nullable<byte> IncludeInPayroll { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<int> DocumentMasterId { get; set; }
        public string Achievements { get; set; }
        public string PANNumber { get; set; }
        public string PFNumber { get; set; }
        public Nullable<System.DateTime> EmployeeLastDate { get; set; }
        public Nullable<bool> IsEmploymentConfirmed { get; set; }
        public Nullable<bool> IsUnderProbation { get; set; }
        public Nullable<System.DateTime> ProbationEndDate { get; set; }
        public Nullable<int> ReportingManagerId { get; set; }
        public Nullable<bool> ApplyTax { get; set; }
        public Nullable<byte> InvitationSent { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
    }
}
