//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using EduRp.Data.Core.Foundation;
    using System;
    using System.Collections.Generic;
    
    public partial class ExamStudentAssociation : BaseEntity
    {
        public int ExamStudentAssociationId { get; set; }
        public Nullable<int> ExaminationScheduleDetailId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
    }
}
