//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationScheduleDetail
    {
        public int ExaminationScheduleDetailId { get; set; }
        public Nullable<int> ExaminationScheduleId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> Staff1Id { get; set; }
        public Nullable<int> Staff2Id { get; set; }
    }
}
