//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportFilterAssociation
    {
        public int ReportFilterAssociationId { get; set; }
        public int ReportId { get; set; }
        public int FilterId { get; set; }
        public byte OrderBy { get; set; }
    }
}
