//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDetail
    {
        public int ReportId { get; set; }
        public string ReportName { get; set; }
        public string ReportTitle { get; set; }
        public string ReportDataSP { get; set; }
        public string Graph1Title { get; set; }
        public string Graph1Type { get; set; }
        public string Graph1DataSP { get; set; }
        public string Graph2Title { get; set; }
        public string Graph2Type { get; set; }
        public string Graph2DataSP { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
        public Nullable<int> MenuId { get; set; }
    }
}
