//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportMenu
    {
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public string MenuType { get; set; }
        public byte MenuOrder { get; set; }
        public string MenuIcon { get; set; }
        public string Navigationurl { get; set; }
        public string PageTitle { get; set; }
        public string SPname { get; set; }
        public byte ParentId { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
    }
}
