//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenMaster
    {
        public int ScreenId { get; set; }
        public string ScreenTitle { get; set; }
        public string ScreenDescription { get; set; }
        public Nullable<int> ScreenOrder { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string NavigationUrl { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
    }
}
