//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tKeyword
    {
        public int Id { get; set; }
        public string Keywords { get; set; }
        public string ActualWords { get; set; }
        public string TemplateName { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    }
}
