//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNotificationLog
    {
        public int NotificationLogID { get; set; }
        public string Type { get; set; }
        public Nullable<int> NotificationID { get; set; }
        public string FromEmailID { get; set; }
        public string ToEmailID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> SendDateTime { get; set; }
    }
}
