//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityMaster
    {
        public int UniversityId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string UniversityName { get; set; }
        public string UniversityCode { get; set; }
        public string UniversityURL { get; set; }
        public string UniversityLogoPath { get; set; }
        public string UniversityParentURL { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<int> CultureId { get; set; }
        public Nullable<int> DateFormatId { get; set; }
        public Nullable<int> DateTimeFormatId { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
    }
}
