//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserUniversityAssociation
    {
        public int UniversityId { get; set; }
        public int UserUniversityAssociationId { get; set; }
        public int UserId { get; set; }
        public bool IsActive { get; set; }
    }
}
