//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduRp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> PassAttemptCount { get; set; }
        public Nullable<System.Guid> AuthenticationToken { get; set; }
        public string LastLoginIPAddress { get; set; }
        public string DefaultLanguage { get; set; }
        public string loginid { get; set; }
        public string PlaintextPWD { get; set; }
        public string DeviceType { get; set; }
        public string DeviceToken { get; set; }
        public string DeviceIdentifier { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<byte> active { get; set; }
        public Nullable<System.DateTime> lastupdateddt { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
    }
}
